### PR TITLE
Update ambulanceservices.json 1.1

### PR DESCRIPTION
**Pull request by Logicwhiz**
added bhim hospital

### CODE REVIEW

**Review by dashing-dev — CHANGES_REQUESTED** [review]
dont use none , just leave it blank

**Comment by Logicwhiz** [comment]
ok , sure

**Comment by Logicwhiz** [comment]
done

**Comment by dashing-dev** [comment]
thanks for the changes

**Comment by dashing-dev** [comment]
keep contributing

**Pull request merged**
